In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl
print(pd.__version__)
print(np.__version__)

1.3.5
1.21.6


Loading dataset

In [7]:
df = pd.read_csv("/kaggle/input/purchage/purchage.csv")
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [28]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(x)
print("_______________________")
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
_______________________
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking care of missing data
#from sklearn.preprocessing import Imputer
#imputer = Imputer(missing_values = 'NaN', strategy = 'median', axis = 0)# mean, median, most_frequent

In [30]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median') # New Style

imputer = imputer.fit(x[:, 1:3])
x[:, 1:3]=imputer.transform(x[:, 1:3])
print("--------- After Handling Missing Values -------------\n")
print(x)

--------- After Handling Missing Values -------------

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Manually Hangling Missing Values

In [36]:
Age=df['Age']
# print(Age)
Salary=df['Salary']
# print(Salary)
df.Salary.median()
df.Age.median()

38.0

 >Country is string type so should be LabelEncoder 

In [50]:
Country = x[:,0]
# print(Country)
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
x[:, 0]=labelencoder_X.fit_transform(x[:, 0])
print(x)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 61000.0]
 [0 35.0 58000.0]
 [2 38.0 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [52]:
# Label Encoding : Features Vector-y

In [54]:
print(y)
labelencoder_y = LabelEncoder()
y=labelencoder_y.fit_transform(y)
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[0 1 0 0 1 1 0 1 0 1]


In [56]:
#2.OneHotEncoder : New Style 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Country column
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
x = ct.fit_transform(x)
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 61000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [57]:
x=x[:,1:]
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [59]:
# Feature Scaling : Feature Matrix - X
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)
print(x)

[[ 1.22474487 -0.65465367 -0.65465367  0.76973439  0.77256767]
 [-0.81649658 -0.65465367  1.52752523 -1.69922498 -1.40879986]
 [-0.81649658  1.52752523 -0.65465367 -1.26352627 -0.86345798]
 [-0.81649658 -0.65465367  1.52752523 -0.10166303 -0.22722578]
 [-0.81649658  1.52752523 -0.65465367  0.18880278 -0.22722578]
 [ 1.22474487 -0.65465367 -0.65465367 -0.53736175 -0.49989673]
 [-0.81649658 -0.65465367  1.52752523 -0.10166303 -1.04523861]
 [ 1.22474487 -0.65465367 -0.65465367  1.35066601  1.40879986]
 [-0.81649658  1.52752523 -0.65465367  1.64113182  1.77236112]
 [ 1.22474487 -0.65465367 -0.65465367 -0.24689594  0.3181161 ]]


In [61]:
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split - old
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state = 0)

In [62]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[-0.81649658 -0.65465367  1.52752523 -1.69922498 -1.40879986]
 [-0.81649658 -0.65465367  1.52752523 -0.10166303 -1.04523861]
 [ 1.22474487 -0.65465367 -0.65465367  1.35066601  1.40879986]
 [-0.81649658 -0.65465367  1.52752523 -0.10166303 -0.22722578]
 [ 1.22474487 -0.65465367 -0.65465367  0.76973439  0.77256767]
 [ 1.22474487 -0.65465367 -0.65465367 -0.53736175 -0.49989673]]
[[-0.81649658  1.52752523 -0.65465367 -1.26352627 -0.86345798]
 [-0.81649658  1.52752523 -0.65465367  1.64113182  1.77236112]
 [-0.81649658  1.52752523 -0.65465367  0.18880278 -0.22722578]
 [ 1.22474487 -0.65465367 -0.65465367 -0.24689594  0.3181161 ]]
[1 0 1 0 0 1]
[0 0 1 1]


LogisticRegression


In [63]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(random_state = 0) 
classifier.fit(X_train, y_train) 

LogisticRegression(random_state=0)

In [65]:
y_pred = classifier.predict(X_test) 

In [66]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred) 
print ("Confusion Matrix : \n", cm) 

Confusion Matrix : 
 [[1 1]
 [1 1]]


In [67]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred)) 

Accuracy :  0.5


SVC

In [68]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train) 

y_pred = svm.predict(X_test) 
cm = confusion_matrix(y_test, y_pred) 
print ("Confusion Matrix : \n", cm)

print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

Confusion Matrix : 
 [[0 2]
 [0 2]]
Accuracy of SVM classifier on training set: 0.83
Accuracy of SVM classifier on test set: 0.50


Decision Tree Classifier

In [69]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)

In [70]:
y_pred = svm.predict(X_test) 
cm = confusion_matrix(y_test, y_pred) 
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[0 2]
 [0 2]]


In [71]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.00
