In [15]:
import numpy as np

In [16]:
print(np.__version__)

1.21.6


In [22]:

x = np.array(200101057)  #0-D Array
print(x.ndim,"D Array")
print(x)

y = np.array([1,2,100,57]) #1-D Array
print(y.ndim,"D Array")
print(y)

z = np.array([[1,2,3,4],[5,6,7,8],[1,1,2,2],[11,12,15,16]]) #2-D Array
print(z.ndim,"D Array")
print(z)

x1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3-D Array
print(x1.ndim,"D Array")
print(x1)

0 D Array
200101057
1 D Array
[  1   2 100  57]
2 D Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  1  2  2]
 [11 12 15 16]]
3 D Array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
x1 = np.array(x1,ndmin=5) #converting 3-D array to 5-D Array
print(x1.ndim,"-D Array")
print(x1)

5 -D Array
[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]]


In [38]:
print("Showing Original array")
print(z)

print("Showing second row")
print(z[1]) #showing 2nd row

print("Showing 2,3,4 row")
print(z[1:4])

print("Showing index 1,2,3 of 1st row")
print(z[0,1:4])

print("Showing index 0,1,2,3 of 1,2 row")
#print(row,col)
#print(row)
print(z[0:2,0:4])

print("---------Accessing---------")
print(z[-2,-1])
print(z[1,1:])
print(z[1,:3])
#Negative slicing
print(z[2,-4:-1])
print("Shape of z",z.shape)

Showing Original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  1  2  2]
 [11 12 15 16]]
Showing second row
[5 6 7 8]
Showing 2,3,4 row
[[ 5  6  7  8]
 [ 1  1  2  2]
 [11 12 15 16]]
Showing index 1,2,3 of 1st row
[2 3 4]
Showing index 0,1,2,3 of 1,2 row
[[1 2 3 4]
 [5 6 7 8]]
---------Accessing---------
2
[6 7 8]
[5 6 7]
[1 1 2]
Shape of z (4, 4)


In [41]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6 7 8]


In [ ]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

In [ ]:
np_height = np.array(height)
np_weight = np.array(weight)
print(np_height, np_weight)
print(type(np_height))

[1.87 1.87 1.82 1.91 1.9  1.85] [81.65 97.52 95.25 92.98 86.18 88.45]
<class 'numpy.ndarray'>

In [ ]:
print(type(height))

In [10]:
bmi = np_weight / np_height **2
print("BMI:",bmi)

NameError: name 'np_weight' is not defined

For filtering which value is greater than 24

In [ ]:
bmi[bmi > 24]

Exercise [
First, convert the list of weights from a list to a Numpy array. Then, convert all of the weights from kilograms to pounds. Use the scalar conversion of 2.2 lbs per kilogram to make your conversion. Lastly, print the resulting array of weights in pounds ]

In [11]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

In [12]:
np_ary = np.array(weight_kg)

#Converting weight kg to pound
np_ary = np_ary*2.2

#print result
print(np_ary)

[179.63  214.544 209.55  204.556 189.596 194.59 ]


Result: [179.63  214.544 209.55  204.556 189.596 194.59 ]