In [113]:
import numpy as np

In [114]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

In [115]:
np_height = np.array(height)
np_weight = np.array(weight)
print(np_height, np_weight)
print(type(np_height))

[1.87 1.87 1.82 1.91 1.9  1.85] [81.65 97.52 95.25 92.98 86.18 88.45]
<class 'numpy.ndarray'>


[1.87 1.87 1.82 1.91 1.9  1.85] [81.65 97.52 95.25 92.98 86.18 88.45]
<class 'numpy.ndarray'>

In [116]:
print(type(height))

<class 'list'>


In [117]:
bmi = np_weight / np_height **2
print("BMI:",bmi)

BMI: [23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


For filtering which value is greater than 24

In [118]:
bmi[bmi > 24]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

Exercise [
First, convert the list of weights from a list to a Numpy array. Then, convert all of the weights from kilograms to pounds. Use the scalar conversion of 2.2 lbs per kilogram to make your conversion. Lastly, print the resulting array of weights in pounds ]

In [119]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

In [120]:
np_ary = np.array(weight_kg)

#Converting weight kg to pound
np_ary = np_ary*2.2

#print result
print(np_ary)

[179.63  214.544 209.55  204.556 189.596 194.59 ]


Result: [179.63  214.544 209.55  204.556 189.596 194.59 ]